locales:
  available: ["en", "vi"]
  default: "en"
users:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  show:
    gravatar_size: 80
  expired: 2
  paginate:
    per_page: 30
gravatar:
  default_size: 50
  size_30: 30
session:
  one: "1"
microposts:
  maximum: 140
  paginate:
    per_page: 20
picture:
  default: 5
  errors: "should be less than 5MB"
  alert: "Maximum file size is 5MB. Please choose a smaller file."
