locales:
  available: ["en", "vi"]
  default: "en"
users:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  show:
    gravatar_size: 80
  expired: 2
gravatar:
  default_size: 50
session:
  one: "1"
